### ISSUE TITLE
I can't figure out how to use it

### ISSUE THREAD

**Issue by AC10** [agentejo/Autopilot#3]
As you told me to, I've looked a bit more on Autopilot, I've installed it in Cockpit, and I've played around with pages, menus and widgets inside Autopilot, but now.... My big question..

What do I do now?
I can't figure out how to use it

But so far, it looks good. Easy to navigate, easy to choose what kind of element you want to create, is it a page, is it a menu item and so on.

**Comment by thinkink** [comment]
You need to rename the .htaccess.txt --> .htaccess and adjust the line 18:

  RewriteRule .* cockpit/modules/addons/Autopilot/frontend-router.php [L]

to 
  RewriteRule .* {path_to_cokcpit}/modules/addons/Autopilot/frontend-router.php [L]

**Comment by AC10** [comment]
Great, thanks!
I didn't see that the .htaccess was made into a txt file

**Comment by AC10** [comment]
@thinkink Could you help me further with this?

**Comment by thinkink** [comment]
What else do you need?

**Comment by AC10** [comment]
I don't know what to do now when I've created a page inside Autopilot

**Comment by thinkink** [comment]
you need to put the .htaccess in the root for rewriting any directions, 
after create menu item (for example a collection) --> named for example start
select an existent collection in your cockpit and save
in the right side of autopilot select homepage ---> start (or your menu item )
go to your root of site --> is ../admin

**Comment by AC10** [comment]
It works!
Yes, thank you
